services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-9081}:8080"
  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL="http://backend:8080"
    ports:
      - "${FRONTEND_PORT:-4001}:3000"
    depends_on:
      - backend
