[variables]
NIXPACKS_JDK_VERSION = '21'

[phases.build]
cmds = ['./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean verify']
cacheDirectories = ['.m2/repository']

[start]
cmd = './mvnw -B -DskipTests spring-boot:run'